### ISSUE TITLE
쪼리핑님끄투어디있어요?끄투다운어디서밧아요??끄투다운어떳개해요?

### ISSUE THREAD

**Issue by wonjinYi** [sunho/graphics#1]
안녕하세요 끄투를사랑하는 초등학생 4학년 이원진입니다. 저는 끄투를 너무조아해서 여기로찾아왔는대 쪼리핑님이안보여요 다운받고싶은데 무료다운 어떳개하는거애요? 무료다운링크좀 알려주시면 정말로 감사하겠습니다 감사합니다. 끄투다운 도와주세요. 쪼리핑님도 어딨는지 알려주세요

**Comment by sunho** [comment]
https://github.com/sunho/vita-data-kit/issues/1

**Comment by hatty163** [comment]
안녕하세요, 아쉽지만 달달한 쪼리핑 호출 서비스는 현재 코로나19의 여파로 이용하실 수 없습니다 ㅠㅠ
저희 가족분들도 "쪼리핑"을 배우고 싶다고 난리도 아닌데, 정말로 안타까운 소식이네요.
모두 다 행복한 "쪼리핑" 되시기 바랍니다~
